name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1

      - name: Checkout the code
        uses: actions/checkout@master
        
      - name: install the dependencies
        run: npm install
      
      - name: install eslint
        run: npm install eslint
        
      - name: install eslint airbnb dependency
        run: npm install eslint-config-airbnb-base

      - name: install eslint plugin import 
        run: npm install eslint-plugin-import

      - name: npm audit action
        run: npm audit
      
      - name: Run lint
        run: npm run lint
        
